### ISSUE TITLE
Annotation filtering on scanning breaks if applying multiple filters with different origins

### ISSUE THREAD

**Issue by kmshin1397** [skyportal/skyportal#1185]
Cannot have multiple filters set on annotation fields from different origins at the same time.

For example, you cannot filter for some_key (origin A): true and some_other_key (origin B): true at the same time even if a candidate has both. This will just result in no results returned. 

Vague impression is that this will require a bigger change to the sqlalchemy code for the candidates handler and more thinking than a quick change. Something like merge annotation rows into one big jsonb field so that one row knows it has both origins? Right now the queries technically look for entries in the Annotation table that have both fields instead of objects with entries in the Annotation table that fit the fields.

**Comment by kmshin1397** [comment]
Discovered and mentioned in #1183

**Comment by dmitryduev** [comment]
Fixed by @kmshin1397, closing.

**Comment by kmshin1397** [comment]
Ah the above PR is where the initial discussion on this issue took place - this is not fixed yet.

**Comment by acrellin** [comment]
We can simply make a note of the limitations of this feature on scanning page
