### ISSUE TITLE
Spectroscopy figure blank

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1556]
A source spectroscopy plot is blank by default.  I am unable to find the spectrum scrolling in the window.  I have confirmed that the spectra do have values.

![image](https://user-images.githubusercontent.com/880156/103585456-ebeae480-4e97-11eb-8f16-4b51362c0722.png)

**Comment by guynir42** [comment]
Hi @AlexGKim can you specify which source this happens on? or are there multiple such cases?

**Comment by AlexGKim** [comment]
Hi @guynir42 .  There is a subset of objects for which this happens, another subset for which the spectra appear fine.

For the subset that does not work, the mean signal is close to zero.  Perhaps this is messing up the automatic scaling.

**Comment by guynir42** [comment]
This was my first guess as well, @AlexGKim 

It would be very useful if you can give me one or two such instances (object IDs are fine) and I will dig into it.

**Comment by AlexGKim** [comment]
The page for the source is as follows:
http://desi2.lbl.gov:5000/source/DESI39628472791861352

It is not public data unfortunately, so I would have give you credentials to see this.  Note that I have another issue #1535 where people with permissions (as far as I can tell) can't view these sources.

**Comment by guynir42** [comment]
Can you send me the spectral flux values for one of the spectra that isn't showing up? 
Or better yet, check what is the median of the flux values?

**Comment by AlexGKim** [comment]
For one of the spectra, the median and standard deviation are 

0.4266241959299460
11.775570707588


--
11.775570707588

**Comment by guynir42** [comment]
The median value is actually not that small, so I don't know if that is the cause. Are there NaN values or something like that?

**Comment by AlexGKim** [comment]
Here is some more information: 

On the plot on the source page nothing appears for the spectra shown together.
In the "Spectroscopy" page for that source I make plots of each spectrum individually.  Some appear, some do not.  Those that do not have median <=0 I think (I have not checked exhaustively).

**Comment by guynir42** [comment]
Ok that makes a lot more sense.

**Comment by guynir42** [comment]
Will be closed by #1558

**Comment by guynir42** [comment]
@AlexGKim if you pull an updated version of SkyPortal this should be resolved (if we are correct about the cause of the bug). 

Let me know if that solves things...

**Comment by AlexGKim** [comment]
I just pulled the blessed version of skyportal and I still have the problem for a spectrum with a negative mean.

**Comment by guynir42** [comment]
I guess it needs a bit more digging. This spectrum has some positive values and some negative?

**Comment by AlexGKim** [comment]
There are both negative and positive values.

Enclosed is a CSV of a spectrum if it is helpful.

[DESI39627689237153356_DESI_2020-12-24T04_54_56.414000.txt](https://github.com/skyportal/skyportal/files/5778297/DESI39627689237153356_DESI_2020-12-24T04_54_56.414000.txt)

**Comment by guynir42** [comment]
@AlexGKim this is very useful, thank you! 
I have now verified the problem was indeed what I thought, I just applied the fix on wrong plot... 
The fix has now been submitted (and tested on my local version, so I think it will work this time). 
It should be updated today/tomorrow. I will keep you posted.

**Comment by guynir42** [comment]
@AlexGKim try pulling the latest SkyPortal. I think it should be ok now.

**Comment by AlexGKim** [comment]
Success!  Thanks.
